"""The catalogue, generated from a working database.

Do not edit by hand -- regenerate with `python scripts/export_catalogue.py`
after making changes through the admin dashboard, then commit this file.

It exists because dev.db is gitignored: without it, cloning the repo onto
another machine rebuilds only a fraction of the shop.
"""

CATEGORIES = [
    {'name': 'Audio', 'slug': 'audio', 'description': None},
    {'name': 'CCTV & Security Cameras', 'slug': 'cctv-security-cameras', 'description': None},
    {'name': 'Computer Accessories', 'slug': 'computer-accessories', 'description': None},
    {'name': 'Desktops', 'slug': 'desktops', 'description': None},
    {'name': 'Feature Phones', 'slug': 'feature-phones', 'description': None},
    {'name': 'GPS & Trackers', 'slug': 'gps-trackers', 'description': None},
    {'name': 'Home Appliances', 'slug': 'home-appliances', 'description': None},
    {'name': 'Installation & Services', 'slug': 'installation-services', 'description': None},
    {'name': 'Laptops', 'slug': 'laptops', 'description': None},
    {'name': 'Money Counting Machines', 'slug': 'money-counting-machines', 'description': None},
    {'name': 'Monitors', 'slug': 'monitors', 'description': None},
    {'name': 'Networking', 'slug': 'networking', 'description': None},
    {'name': 'Paper Shredders', 'slug': 'paper-shredders', 'description': None},
    {'name': 'Phone Accessories', 'slug': 'phone-accessories', 'description': None},
    {'name': 'Printers', 'slug': 'printers', 'description': None},
    {'name': 'Projectors', 'slug': 'projectors', 'description': None},
    {'name': 'Scanners', 'slug': 'scanners', 'description': None},
    {'name': 'Smartphones', 'slug': 'smartphones', 'description': None},
    {'name': 'Sound Bars', 'slug': 'sound-bars', 'description': None},
    {'name': 'Tablets', 'slug': 'tablets', 'description': None},
    {'name': 'Toner & Ink', 'slug': 'toner-ink', 'description': None},
    {'name': 'UPS', 'slug': 'ups', 'description': None},
]

PRODUCTS = [
    {
        'name': 'Aurora X12 Smartphone',
        'slug': 'aurora-x12-smartphone',
        'description': '6.5-inch AMOLED display, 128GB storage, triple camera system.',
        'price': 588000,
        'compare_at_price': 660000,
        'sku': 'AUR-X12',
        'stock_quantity': 25,
        'is_active': True,
        'category_slug': 'smartphones',
        'images': [{'url': '/products/aurora-x12-smartphone.jpg', 'alt_text': 'Aurora X12 Smartphone', 'position': 0}],
    },
    {
        'name': 'Zenith S9 Smartphone',
        'slug': 'zenith-s9-smartphone',
        'description': '6.7-inch OLED, 256GB storage, 5G, 108MP main camera.',
        'price': 924000,
        'compare_at_price': None,
        'sku': 'ZEN-S9',
        'stock_quantity': 18,
        'is_active': True,
        'category_slug': 'smartphones',
        'images': [{'url': '/products/zenith-s9-smartphone.jpg', 'alt_text': 'Zenith S9 Smartphone', 'position': 0}],
    },
    {
        'name': 'Comet Lite Smartphone',
        'slug': 'comet-lite-smartphone',
        'description': 'Budget-friendly 6.1-inch display, 64GB storage, all-day battery.',
        'price': 235000,
        'compare_at_price': 276000,
        'sku': 'COM-LITE',
        'stock_quantity': 40,
        'is_active': True,
        'category_slug': 'smartphones',
        'images': [{'url': '/products/comet-lite-smartphone.jpg', 'alt_text': 'Comet Lite Smartphone', 'position': 0}],
    },
    {
        'name': 'Nimbus Pro 14 Laptop',
        'slug': 'nimbus-pro-14-laptop',
        'description': '14-inch laptop, 16GB RAM, 512GB SSD, all-day battery life.',
        'price': 1488000,
        'compare_at_price': None,
        'sku': 'NIM-PRO14',
        'stock_quantity': 12,
        'is_active': True,
        'category_slug': 'laptops',
        'images': [{'url': '/products/nimbus-pro-14-laptop.jpg', 'alt_text': 'Nimbus Pro 14 Laptop', 'position': 0}],
    },
    {
        'name': 'Titan 15 Gaming Laptop',
        'slug': 'titan-15-gaming-laptop',
        'description': '15.6-inch 144Hz display, RTX graphics, 32GB RAM, 1TB SSD.',
        'price': 3480000,
        'compare_at_price': 3840000,
        'sku': 'TIT-G15',
        'stock_quantity': 6,
        'is_active': True,
        'category_slug': 'laptops',
        'images': [{'url': '/products/titan-15-gaming-laptop.jpg', 'alt_text': 'Titan 15 Gaming Laptop', 'position': 0}],
    },
    {
        'name': 'Slimline Air 13 Ultrabook',
        'slug': 'slimline-air-13-ultrabook',
        'description': '13-inch ultra-light 1.1kg laptop, 8GB RAM, 256GB SSD.',
        'price': 1152000,
        'compare_at_price': None,
        'sku': 'SLM-AIR13',
        'stock_quantity': 15,
        'is_active': True,
        'category_slug': 'laptops',
        'images': [{'url': '/products/slimline-air-13-ultrabook.jpg', 'alt_text': 'Slimline Air 13 Ultrabook', 'position': 0}],
    },
    {
        'name': 'Vertex Tower i7 Desktop',
        'slug': 'vertex-tower-i7-desktop',
        'description': 'Intel i7, 16GB RAM, 1TB SSD, dedicated graphics -- ready for work or play.',
        'price': 1872000,
        'compare_at_price': None,
        'sku': 'VTX-I7',
        'stock_quantity': 8,
        'is_active': True,
        'category_slug': 'desktops',
        'images': [{'url': '/products/vertex-tower-i7-desktop.jpg', 'alt_text': 'Vertex Tower i7 Desktop', 'position': 0}],
    },
    {
        'name': 'Compact Mini PC',
        'slug': 'compact-mini-pc',
        'description': 'Space-saving mini desktop, 8GB RAM, 256GB SSD -- ideal for offices.',
        'price': 768000,
        'compare_at_price': 840000,
        'sku': 'CMP-MINI',
        'stock_quantity': 20,
        'is_active': True,
        'category_slug': 'desktops',
        'images': [{'url': '/products/compact-mini-pc.jpg', 'alt_text': 'Compact Mini PC', 'position': 0}],
    },
    {
        'name': 'Workstation Pro X',
        'slug': 'workstation-pro-x',
        'description': 'High-performance workstation for design and video editing, 32GB RAM, 2TB SSD.',
        'price': 4440000,
        'compare_at_price': None,
        'sku': 'WKS-PROX',
        'stock_quantity': 4,
        'is_active': True,
        'category_slug': 'desktops',
        'images': [{'url': '/products/workstation-pro-x.png', 'alt_text': 'Workstation Pro X', 'position': 0}],
    },
    {
        'name': 'TrackSafe GPS Vehicle Tracker',
        'slug': 'tracksafe-gps-vehicle-tracker',
        'description': 'Real-time GPS vehicle tracking with mobile app, geofencing, and theft alerts.',
        'price': 108000,
        'compare_at_price': None,
        'sku': 'TRK-VEH01',
        'stock_quantity': 30,
        'is_active': True,
        'category_slug': 'gps-trackers',
        'images': [{'url': '/products/tracksafe-gps-vehicle-tracker.jpg', 'alt_text': 'TrackSafe GPS Vehicle Tracker', 'position': 0}],
    },
    {
        'name': 'NaviPro Handheld GPS',
        'slug': 'navipro-handheld-gps',
        'description': 'Rugged handheld GPS navigator for outdoor and off-road use.',
        'price': 163000,
        'compare_at_price': 190000,
        'sku': 'NAV-HAND01',
        'stock_quantity': 14,
        'is_active': True,
        'category_slug': 'gps-trackers',
        'images': [{'url': '/products/navipro-handheld-gps.jpg', 'alt_text': 'NaviPro Handheld GPS', 'position': 0}],
    },
    {
        'name': 'FleetGuard Mini GPS Tracker',
        'slug': 'fleetguard-mini-gps-tracker',
        'description': 'Compact GPS tracker for motorcycles and bikes, long battery life.',
        'price': 67000,
        'compare_at_price': None,
        'sku': 'FLT-MINI01',
        'stock_quantity': 4,
        'is_active': True,
        'category_slug': 'gps-trackers',
        'images': [{'url': '/products/fleetguard-mini-gps-tracker.jpg', 'alt_text': 'FleetGuard Mini GPS Tracker', 'position': 0}],
    },
    {
        'name': 'Hikvision 4-Channel PoE NVR Kit',
        'slug': 'hikvision-4-channel-poe-nvr-kit',
        'description': 'Genuine Hikvision 4-channel PoE NVR with matching HD cameras, night vision and remote mobile viewing.',
        'price': 396000,
        'compare_at_price': 468000,
        'sku': 'SEC-4CH',
        'stock_quantity': 10,
        'is_active': True,
        'category_slug': 'cctv-security-cameras',
        'images': [{'url': '/products/hikvision-4-channel-poe-nvr-kit.png', 'alt_text': 'Hikvision 4-Channel PoE NVR Kit', 'position': 0}],
    },
    {
        'name': 'Hikvision Outdoor Dome Network Camera',
        'slug': 'hikvision-outdoor-dome-network-camera',
        'description': 'Genuine Hikvision PoE dome network camera, weatherproof housing, night vision, two-way audio.',
        'price': 77000,
        'compare_at_price': None,
        'sku': 'NGT-WIP01',
        'stock_quantity': 22,
        'is_active': True,
        'category_slug': 'cctv-security-cameras',
        'images': [{'url': '/products/hikvision-outdoor-dome-network-camera.jpg', 'alt_text': 'Hikvision Outdoor Dome Network Camera', 'position': 0}],
    },
    {
        'name': 'Hikvision TandemVu PTZ Camera',
        'slug': 'hikvision-tandemvu-ptz-camera',
        'description': 'Genuine Hikvision TandemVu pan-tilt-zoom camera, combining panoramic and detail views with long-range night vision.',
        'price': 130000,
        'compare_at_price': None,
        'sku': 'DOM-OUT01',
        'stock_quantity': 16,
        'is_active': True,
        'category_slug': 'cctv-security-cameras',
        'images': [{'url': '/products/hikvision-tandemvu-ptz-camera.jpg', 'alt_text': 'Hikvision TandemVu PTZ Camera', 'position': 0}],
    },
    {
        'name': 'Hikvision Video Intercom Doorbell',
        'slug': 'hikvision-video-intercom-doorbell',
        'description': 'Genuine Hikvision video door intercom with camera and card access lock, two-way audio and mobile alerts.',
        'price': 98000,
        'compare_at_price': 115000,
        'sku': 'SMT-DOOR01',
        'stock_quantity': 3,
        'is_active': True,
        'category_slug': 'cctv-security-cameras',
        'images': [{'url': '/products/hikvision-video-intercom-doorbell.jpg', 'alt_text': 'Hikvision Video Intercom Doorbell', 'position': 0}],
    },
    {
        'name': 'Pulse Wireless Earbuds',
        'slug': 'pulse-wireless-earbuds',
        'description': 'Active noise cancellation, 30-hour battery with charging case.',
        'price': 91000,
        'compare_at_price': 108000,
        'sku': 'PLS-EB01',
        'stock_quantity': 60,
        'is_active': True,
        'category_slug': 'audio',
        'images': [{'url': '/products/pulse-wireless-earbuds.jpg', 'alt_text': 'Pulse Wireless Earbuds', 'position': 0}],
    },
    {
        'name': 'BassBoost Bluetooth Speaker',
        'slug': 'bassboost-bluetooth-speaker',
        'description': 'Portable waterproof Bluetooth speaker with deep bass and 12-hour battery.',
        'price': 62000,
        'compare_at_price': None,
        'sku': 'BSB-SPK01',
        'stock_quantity': 35,
        'is_active': True,
        'category_slug': 'audio',
        'images': [{'url': '/products/bassboost-bluetooth-speaker.jpg', 'alt_text': 'BassBoost Bluetooth Speaker', 'position': 0}],
    },
    {
        'name': 'VoltCharge 65W Fast Charger',
        'slug': 'voltcharge-65w-fast-charger',
        'description': 'Universal USB-C GaN fast charger, compatible with phones and laptops.',
        'price': 37000,
        'compare_at_price': None,
        'sku': 'VLT-65W',
        'stock_quantity': 3,
        'is_active': True,
        'category_slug': 'phone-accessories',
        'images': [{'url': '/products/voltcharge-65w-fast-charger.jpg', 'alt_text': 'VoltCharge 65W Fast Charger', 'position': 0}],
    },
    {
        'name': 'ArmorShield Phone Case',
        'slug': 'armorshield-phone-case',
        'description': 'Military-grade drop protection case, available for major phone models.',
        'price': 20000,
        'compare_at_price': 29000,
        'sku': 'ARM-CASE01',
        'stock_quantity': 80,
        'is_active': True,
        'category_slug': 'phone-accessories',
        'images': [{'url': '/products/armorshield-phone-case.jpg', 'alt_text': 'ArmorShield Phone Case', 'position': 0}],
    },
    {
        'name': 'ClearView Tempered Glass Screen Protector',
        'slug': 'clearview-tempered-glass-screen-protector',
        'description': '9H hardness tempered glass, bubble-free installation, 2-pack.',
        'price': 8000,
        'compare_at_price': None,
        'sku': 'CLR-GLASS01',
        'stock_quantity': 120,
        'is_active': True,
        'category_slug': 'phone-accessories',
        'images': [{'url': '/products/clearview-tempered-glass-screen-protector.png', 'alt_text': 'ClearView Tempered Glass Screen Protector', 'position': 0}],
    },
    {
        'name': 'FlexMount Car Phone Holder',
        'slug': 'flexmount-car-phone-holder',
        'description': '360-degree rotating dashboard and vent phone mount.',
        'price': 15000,
        'compare_at_price': None,
        'sku': 'FLX-MOUNT01',
        'stock_quantity': 5,
        'is_active': True,
        'category_slug': 'phone-accessories',
        'images': [{'url': '/products/flexmount-car-phone-holder.jpg', 'alt_text': 'FlexMount Car Phone Holder', 'position': 0}],
    },
    {
        'name': 'ErgoType Wireless Keyboard & Mouse Combo',
        'slug': 'ergotype-wireless-keyboard-mouse-combo',
        'description': 'Comfortable wireless keyboard and mouse set, 18-month battery life.',
        'price': 53000,
        'compare_at_price': 62000,
        'sku': 'ERG-COMBO01',
        'stock_quantity': 28,
        'is_active': True,
        'category_slug': 'computer-accessories',
        'images': [{'url': '/products/ergotype-wireless-keyboard-mouse-combo.jpg', 'alt_text': 'ErgoType Wireless Keyboard & Mouse Combo', 'position': 0}],
    },
    {
        'name': 'ClickPro Wireless Mouse',
        'slug': 'clickpro-wireless-mouse',
        'description': 'Precision wireless mouse with silent clicks and adjustable DPI.',
        'price': 23000,
        'compare_at_price': None,
        'sku': 'CLK-MOUSE01',
        'stock_quantity': 45,
        'is_active': True,
        'category_slug': 'computer-accessories',
        'images': [{'url': '/products/clickpro-wireless-mouse.jpg', 'alt_text': 'ClickPro Wireless Mouse', 'position': 0}],
    },
    {
        'name': 'ViewMax 27" Monitor',
        'slug': 'viewmax-27-monitor',
        'description': '27-inch Full HD IPS monitor, ideal for work and everyday computing.',
        'price': 348000,
        'compare_at_price': 396000,
        'sku': 'VWM-27FHD',
        'stock_quantity': 9,
        'is_active': True,
        'category_slug': 'computer-accessories',
        'images': [{'url': '/products/viewmax-27-monitor.jpg', 'alt_text': 'ViewMax 27" Monitor', 'position': 0}],
    },
    {
        'name': 'SwiftHub USB-C Docking Station',
        'slug': 'swifthub-usb-c-docking-station',
        'description': '9-in-1 USB-C hub with HDMI, USB 3.0, SD card reader, and PD charging.',
        'price': 66000,
        'compare_at_price': None,
        'sku': 'SWF-HUB01',
        'stock_quantity': 17,
        'is_active': True,
        'category_slug': 'computer-accessories',
        'images': [{'url': '/products/swifthub-usb-c-docking-station.jpg', 'alt_text': 'SwiftHub USB-C Docking Station', 'position': 0}],
    },
    {
        'name': 'Infinix NOTE 60 Pro 5G, 8GB RAM, 256GB',
        'slug': 'infinix-note-60-pro-5g-8gb-ram-256gb',
        'description': '6.78-inch display, 8GB RAM, 256GB storage, 5G connectivity.',
        'price': 1510000,
        'compare_at_price': 1950000,
        'sku': 'INF-N60PRO',
        'stock_quantity': 12,
        'is_active': True,
        'category_slug': 'smartphones',
        'images': [{'url': '/products/infinix-note-60-pro-5g-8gb-ram-256gb.jpg', 'alt_text': 'Infinix NOTE 60 Pro 5G, 8GB RAM, 256GB', 'position': 0}],
    },
    {
        'name': 'Infinix Note Edge 5G (256GB + 8GB RAM) 6.78"',
        'slug': 'infinix-note-edge-5g-256gb-8gb-ram-6-78',
        'description': '6.78-inch display, 8GB RAM, 256GB storage, 5G connectivity.',
        'price': 1170000,
        'compare_at_price': 1500000,
        'sku': 'INF-NEDGE5G',
        'stock_quantity': 14,
        'is_active': True,
        'category_slug': 'smartphones',
        'images': [{'url': '/products/infinix-note-edge-5g-256gb-8gb-ram-6-78.jpg', 'alt_text': 'Infinix Note Edge 5G (256GB + 8GB RAM) 6.78"', 'position': 0}],
    },
    {
        'name': 'Infinix Smart 20 (4GB RAM + 64GB Storage)',
        'slug': 'infinix-smart-20-4gb-ram-64gb-storage',
        'description': 'Budget-friendly display, 4GB RAM, 64GB storage.',
        'price': 429000,
        'compare_at_price': 450000,
        'sku': 'INF-SMART20',
        'stock_quantity': 30,
        'is_active': True,
        'category_slug': 'smartphones',
        'images': [{'url': '/products/infinix-smart-20-4gb-ram-64gb-storage.jpg', 'alt_text': 'Infinix Smart 20 (4GB RAM + 64GB Storage)', 'position': 0}],
    },
    {
        'name': 'Tecno Spark Slim 6.78" AMOLED 144Hz - Helio',
        'slug': 'tecno-spark-slim-6-78-amoled-144hz-helio',
        'description': '6.78-inch AMOLED, 144Hz refresh rate, Helio chipset.',
        'price': 929000,
        'compare_at_price': 1200000,
        'sku': 'TEC-SPARKSLIM',
        'stock_quantity': 10,
        'is_active': True,
        'category_slug': 'smartphones',
        'images': [{'url': '/products/tecno-spark-slim-6-78-amoled-144hz-helio.png', 'alt_text': 'Tecno Spark Slim 6.78" AMOLED 144Hz - Helio', 'position': 0}],
    },
    {
        'name': 'Tecno Spark Go 2 64GB ROM + 4GB RAM - T7250',
        'slug': 'tecno-spark-go-2-64gb-rom-4gb-ram-t7250',
        'description': '64GB storage, 4GB RAM, everyday performance chipset.',
        'price': 369000,
        'compare_at_price': 400000,
        'sku': 'TEC-SPARKGO2',
        'stock_quantity': 20,
        'is_active': True,
        'category_slug': 'smartphones',
        'images': [{'url': '/products/tecno-spark-go-2-64gb-rom-4gb-ram-t7250.png', 'alt_text': 'Tecno Spark Go 2 64GB ROM + 4GB RAM - T7250', 'position': 0}],
    },
    {
        'name': 'Apple iPhone 17 Pro Max 1TB - A19 Pro Chip',
        'slug': 'apple-iphone-17-pro-max-1tb-a19-pro-chip',
        'description': "1TB storage, A19 Pro chip, Apple's flagship camera system.",
        'price': 7600000,
        'compare_at_price': 7900000,
        'sku': 'APL-17PM-1TB',
        'stock_quantity': 3,
        'is_active': True,
        'category_slug': 'smartphones',
        'images': [{'url': '/products/apple-iphone-17-pro-max-1tb-a19-pro-chip.jpg', 'alt_text': 'Apple iPhone 17 Pro Max 1TB - A19 Pro Chip', 'position': 0}],
    },
    {
        'name': 'Apple iPhone 17 Pro Max 512GB - A19 Pro Chip',
        'slug': 'apple-iphone-17-pro-max-512gb-a19-pro-chip',
        'description': "512GB storage, A19 Pro chip, Apple's flagship camera system.",
        'price': 6600000,
        'compare_at_price': 7200000,
        'sku': 'APL-17PM-512',
        'stock_quantity': 5,
        'is_active': True,
        'category_slug': 'smartphones',
        'images': [{'url': '/products/apple-iphone-17-pro-max-512gb-a19-pro-chip.jpg', 'alt_text': 'Apple iPhone 17 Pro Max 512GB - A19 Pro Chip', 'position': 0}],
    },
    {
        'name': 'Tecno MegaPad SE 11" Tablet - 4GB RAM',
        'slug': 'tecno-megapad-se-11-tablet-4gb-ram',
        'description': '11-inch display, 4GB RAM, everyday tablet for work and entertainment.',
        'price': 629000,
        'compare_at_price': 650000,
        'sku': 'TEC-MEGAPADSE',
        'stock_quantity': 8,
        'is_active': True,
        'category_slug': 'tablets',
        'images': [{'url': '/products/tecno-megapad-se-11-tablet-4gb-ram.jpg', 'alt_text': 'Tecno MegaPad SE 11" Tablet - 4GB RAM', 'position': 0}],
    },
    {
        'name': 'Samsung Galaxy Tab A11 8.7-Inch Tablet',
        'slug': 'samsung-galaxy-tab-a11-8-7-inch-tablet',
        'description': '8.7-inch display, everyday tablet for browsing, media and study.',
        'price': 750000,
        'compare_at_price': 800000,
        'sku': 'SAM-TABA11',
        'stock_quantity': 15,
        'is_active': True,
        'category_slug': 'tablets',
        'images': [{'url': '/products/samsung-galaxy-tab-a11-8-7-inch-tablet.jpg', 'alt_text': 'Samsung Galaxy Tab A11 8.7-Inch Tablet', 'position': 0}],
    },
    {
        'name': 'Apple iPad Pro 11-inch M4 Wi-Fi + 5G Cellular',
        'slug': 'apple-ipad-pro-11-inch-m4-wi-fi-5g-cellular',
        'description': '11-inch iPad Pro, M4 chip, Wi-Fi + 5G Cellular.',
        'price': 4600000,
        'compare_at_price': 4900000,
        'sku': 'APL-IPADPRO11M4',
        'stock_quantity': 4,
        'is_active': True,
        'category_slug': 'tablets',
        'images': [{'url': '/products/apple-ipad-pro-11-inch-m4-wi-fi-5g-cellular.jpg', 'alt_text': 'Apple iPad Pro 11-inch M4 Wi-Fi + 5G Cellular', 'position': 0}],
    },
    {
        'name': 'Apple iPad Air M3 13-inch Wi-Fi + 5G Cellular',
        'slug': 'apple-ipad-air-m3-13-inch-wi-fi-5g-cellular',
        'description': '13-inch iPad Air, M3 chip, Wi-Fi + 5G Cellular.',
        'price': 3050000,
        'compare_at_price': 3250000,
        'sku': 'APL-IPADAIRM3-13',
        'stock_quantity': 5,
        'is_active': True,
        'category_slug': 'tablets',
        'images': [{'url': '/products/apple-ipad-air-m3-13-inch-wi-fi-5g-cellular.jpg', 'alt_text': 'Apple iPad Air M3 13-inch Wi-Fi + 5G Cellular', 'position': 0}],
    },
    {
        'name': 'Apple iPad Air M3 11-inch Wi-Fi + 5G Cellular',
        'slug': 'apple-ipad-air-m3-11-inch-wi-fi-5g-cellular',
        'description': '11-inch iPad Air, M3 chip, Wi-Fi + 5G Cellular.',
        'price': 3400000,
        'compare_at_price': 3600000,
        'sku': 'APL-IPADAIRM3-11',
        'stock_quantity': 6,
        'is_active': True,
        'category_slug': 'tablets',
        'images': [{'url': '/products/apple-ipad-air-m3-11-inch-wi-fi-5g-cellular.jpg', 'alt_text': 'Apple iPad Air M3 11-inch Wi-Fi + 5G Cellular', 'position': 0}],
    },
    {
        'name': 'Tecno T403 Dual SIM 2.4" Display - 4MB RAM, 4MB',
        'slug': 'tecno-t403-dual-sim-2-4-display-4mb-ram-4mb',
        'description': '2.4-inch display, dual SIM, stylish metal design.',
        'price': 75000,
        'compare_at_price': 85000,
        'sku': 'TEC-T403',
        'stock_quantity': 25,
        'is_active': True,
        'category_slug': 'feature-phones',
        'images': [{'url': '/products/tecno-t403-dual-sim-2-4-display-4mb-ram-4mb.jpg', 'alt_text': 'Tecno T403 Dual SIM 2.4" Display - 4MB RAM, 4MB', 'position': 0}],
    },
    {
        'name': 'Tecno T313 Dual SIM 1.77" Display - 4MB',
        'slug': 'tecno-t313-dual-sim-1-77-display-4mb',
        'description': '1.77-inch display, dual SIM, long standby battery.',
        'price': 80000,
        'compare_at_price': 96000,
        'sku': 'TEC-T313',
        'stock_quantity': 25,
        'is_active': True,
        'category_slug': 'feature-phones',
        'images': [{'url': '/products/tecno-t313-dual-sim-1-77-display-4mb.jpg', 'alt_text': 'Tecno T313 Dual SIM 1.77" Display - 4MB', 'position': 0}],
    },
    {
        'name': 'Tecno T315 Dual SIM 2.4" QQVGA Display - 4MB',
        'slug': 'tecno-t315-dual-sim-2-4-qqvga-display-4mb',
        'description': '2.4-inch QQVGA display, dual SIM.',
        'price': 80000,
        'compare_at_price': 95000,
        'sku': 'TEC-T315',
        'stock_quantity': 25,
        'is_active': True,
        'category_slug': 'feature-phones',
        'images': [{'url': '/products/tecno-t315-dual-sim-2-4-qqvga-display-4mb.jpg', 'alt_text': 'Tecno T315 Dual SIM 2.4" QQVGA Display - 4MB', 'position': 0}],
    },
    {
        'name': 'Tecno T353 Dual SIM 2.4" QQVGA Display - 4MB',
        'slug': 'tecno-t353-dual-sim-2-4-qqvga-display-4mb',
        'description': '2.4-inch QQVGA display, dual SIM.',
        'price': 90000,
        'compare_at_price': 100000,
        'sku': 'TEC-T353',
        'stock_quantity': 20,
        'is_active': True,
        'category_slug': 'feature-phones',
        'images': [{'url': '/products/tecno-t353-dual-sim-2-4-qqvga-display-4mb.jpg', 'alt_text': 'Tecno T353 Dual SIM 2.4" QQVGA Display - 4MB', 'position': 0}],
    },
    {
        'name': 'Tecno T352 Dual SIM 1.77" Display - 4MB',
        'slug': 'tecno-t352-dual-sim-1-77-display-4mb',
        'description': '1.77-inch display, dual SIM.',
        'price': 65000,
        'compare_at_price': 75000,
        'sku': 'TEC-T352',
        'stock_quantity': 20,
        'is_active': True,
        'category_slug': 'feature-phones',
        'images': [{'url': '/products/tecno-t352-dual-sim-1-77-display-4mb.jpg', 'alt_text': 'Tecno T352 Dual SIM 1.77" Display - 4MB', 'position': 0}],
    },
    {
        'name': 'Tecno T485 Dual SIM 2.8" Display - 4MB RAM, 4MB',
        'slug': 'tecno-t485-dual-sim-2-8-display-4mb-ram-4mb',
        'description': '2.8-inch display, dual SIM.',
        'price': 140000,
        'compare_at_price': 190000,
        'sku': 'TEC-T485',
        'stock_quantity': 15,
        'is_active': True,
        'category_slug': 'feature-phones',
        'images': [{'url': '/products/tecno-t485-dual-sim-2-8-display-4mb-ram-4mb.jpg', 'alt_text': 'Tecno T485 Dual SIM 2.8" Display - 4MB RAM, 4MB', 'position': 0}],
    },
    {
        'name': 'Tecno T529 Dual SIM 2.8" Display - 16MB ROM',
        'slug': 'tecno-t529-dual-sim-2-8-display-16mb-rom',
        'description': '2.8-inch display, dual SIM, 16MB ROM.',
        'price': 95000,
        'compare_at_price': 105000,
        'sku': 'TEC-T529',
        'stock_quantity': 18,
        'is_active': True,
        'category_slug': 'feature-phones',
        'images': [{'url': '/products/tecno-t529-dual-sim-2-8-display-16mb-rom.jpg', 'alt_text': 'Tecno T529 Dual SIM 2.8" Display - 16MB ROM', 'position': 0}],
    },
    {
        'name': 'Tecno T663 Dual SIM 3.5" Touchscreen - 128MB',
        'slug': 'tecno-t663-dual-sim-3-5-touchscreen-128mb',
        'description': '3.5-inch touchscreen, dual SIM, 128MB storage.',
        'price': 135000,
        'compare_at_price': 150000,
        'sku': 'TEC-T663',
        'stock_quantity': 12,
        'is_active': True,
        'category_slug': 'feature-phones',
        'images': [{'url': '/products/tecno-t663-dual-sim-3-5-touchscreen-128mb.jpg', 'alt_text': 'Tecno T663 Dual SIM 3.5" Touchscreen - 128MB', 'position': 0}],
    },
    {
        'name': 'Tecno T455 Dual SIM 2.8" Display, 128MB ROM',
        'slug': 'tecno-t455-dual-sim-2-8-display-128mb-rom',
        'description': '2.8-inch display, dual SIM, 128MB ROM.',
        'price': 95000,
        'compare_at_price': 105000,
        'sku': 'TEC-T455',
        'stock_quantity': 18,
        'is_active': True,
        'category_slug': 'feature-phones',
        'images': [{'url': '/products/tecno-t455-dual-sim-2-8-display-128mb-rom.jpg', 'alt_text': 'Tecno T455 Dual SIM 2.8" Display, 128MB ROM', 'position': 0}],
    },
    {
        'name': 'Lenovo ThinkCentre Neo 50a Gen 5 27" All-in-One',
        'slug': 'lenovo-thinkcentre-neo-50a-gen-5-27-all-in-one',
        'description': '27-inch all-in-one desktop PC.',
        'price': 4023000,
        'compare_at_price': 4300000,
        'sku': 'LEN-TCN50A-G5-27',
        'stock_quantity': 6,
        'is_active': True,
        'category_slug': 'desktops',
        'images': [{'url': '/products/lenovo-thinkcentre-neo-50a-gen-5-27-all-in-one.jpg', 'alt_text': 'Lenovo ThinkCentre Neo 50a Gen 5 27" All-in-One', 'position': 0}],
    },
    {
        'name': 'Lenovo IdeaPad Slim 3 14AMN8 14" Laptop',
        'slug': 'lenovo-ideapad-slim-3-14amn8-14-laptop',
        'description': '14-inch everyday laptop.',
        'price': 2185000,
        'compare_at_price': 2300000,
        'sku': 'LEN-IPS3-14AMN8',
        'stock_quantity': 10,
        'is_active': True,
        'category_slug': 'laptops',
        'images': [{'url': '/products/8.webp', 'alt_text': 'Lenovo IdeaPad Slim 3 14AMN8 14" Laptop', 'position': 0}],
    },
    {
        'name': 'HP ProBook 4 G1iR 16" Laptop | Intel Core 5',
        'slug': 'hp-probook-4-g1ir-16-laptop-intel-core-5',
        'description': '16-inch business laptop, Intel Core 5.',
        'price': 3776000,
        'compare_at_price': 4000000,
        'sku': 'HP-PB4-G1IR-16',
        'stock_quantity': 8,
        'is_active': True,
        'category_slug': 'laptops',
        'images': [{'url': '/products/1.jpg', 'alt_text': 'HP ProBook 4 G1iR 16" Laptop | Intel Core 5', 'position': 0}, {'url': '/products/2.jpg', 'alt_text': 'HP ProBook 4 G1iR 16" Laptop | Intel Core 5', 'position': 1}],
    },
    {
        'name': 'HP ProBook 4 G1iR 14" Laptop Intel Core 5 120U',
        'slug': 'hp-probook-4-g1ir-14-laptop-intel-core-5-120u',
        'description': '14-inch business laptop, Intel Core 5 120U.',
        'price': 3776000,
        'compare_at_price': 4000000,
        'sku': 'HP-PB4-G1IR-14',
        'stock_quantity': 8,
        'is_active': True,
        'category_slug': 'laptops',
        'images': [{'url': '/products/owner-3.jpg', 'alt_text': 'HP ProBook 4 G1iR 14" Laptop Intel Core 5 120U', 'position': 0}, {'url': '/products/3.jpg', 'alt_text': 'HP ProBook 4 G1iR 14" Laptop Intel Core 5 120U', 'position': 1}],
    },
    {
        'name': 'HP ProBook 4 G1i 16" WUXGA Laptop | Intel',
        'slug': 'hp-probook-4-g1i-16-wuxga-laptop-intel',
        'description': '16-inch WUXGA business laptop.',
        'price': 4023000,
        'compare_at_price': 4300000,
        'sku': 'HP-PB4-G1I-16',
        'stock_quantity': 6,
        'is_active': True,
        'category_slug': 'laptops',
        'images': [{'url': '/products/owner-4.jpg', 'alt_text': 'HP ProBook 4 G1i 16" WUXGA Laptop | Intel', 'position': 0}, {'url': '/products/5.webp', 'alt_text': 'HP ProBook 4 G1i 16" WUXGA Laptop | Intel', 'position': 1}],
    },
    {
        'name': 'Lenovo ThinkCentre Neo 50a Gen 5 24" FHD All-in-One',
        'slug': 'lenovo-thinkcentre-neo-50a-gen-5-24-fhd-all-in-one',
        'description': '24-inch FHD all-in-one desktop PC.',
        'price': 3867000,
        'compare_at_price': 4000000,
        'sku': 'LEN-TCN50A-G5-24',
        'stock_quantity': 7,
        'is_active': True,
        'category_slug': 'desktops',
        'images': [{'url': '/products/lenovo-thinkcentre-neo-50a-gen-5-24-fhd-all-in-one.jpg', 'alt_text': 'Lenovo ThinkCentre Neo 50a Gen 5 24" FHD All-in-One', 'position': 0}],
    },
    {
        'name': 'Lenovo ThinkCentre Neo 50a Gen 5 24" FHD Multi-touch',
        'slug': 'lenovo-thinkcentre-neo-50a-gen-5-24-fhd-multi-touch',
        'description': '24-inch FHD multi-touch all-in-one desktop PC.',
        'price': 4000000,
        'compare_at_price': 4300000,
        'sku': 'LEN-TCN50A-G5-24MT',
        'stock_quantity': 5,
        'is_active': True,
        'category_slug': 'desktops',
        'images': [{'url': '/products/lenovo-thinkcentre-neo-50a-gen-5-24-fhd-multi-touch.jpg', 'alt_text': 'Lenovo ThinkCentre Neo 50a Gen 5 24" FHD Multi-touch', 'position': 0}],
    },
    {
        'name': 'HP OMEN Transcend 14 Voco 25C1 Intel Core',
        'slug': 'hp-omen-transcend-14-voco-25c1-intel-core',
        'description': '14-inch gaming laptop, Intel Core.',
        'price': 9068000,
        'compare_at_price': 9250000,
        'sku': 'HP-OMEN-TRANS14',
        'stock_quantity': 3,
        'is_active': True,
        'category_slug': 'laptops',
        'images': [{'url': '/products/7.webp', 'alt_text': 'HP OMEN Transcend 14 Voco 25C1 Intel Core', 'position': 0}],
    },
    {
        'name': 'HP OMEN Hanna 16 Gaming Laptop Intel',
        'slug': 'hp-omen-hanna-16-gaming-laptop-intel',
        'description': '16-inch gaming laptop, Intel.',
        'price': 11535000,
        'compare_at_price': 12000000,
        'sku': 'HP-OMEN-HANNA16',
        'stock_quantity': 0,
        'is_active': True,
        'category_slug': 'laptops',
        'images': [{'url': '/products/6.webp', 'alt_text': 'HP OMEN Hanna 16 Gaming Laptop Intel', 'position': 0}],
    },
    {
        'name': 'HP HyperX OMEN 15-ga0005TX Gaming',
        'slug': 'hp-hyperx-omen-15-ga0005tx-gaming',
        'description': '15-inch gaming laptop, HyperX edition.',
        'price': 8844000,
        'compare_at_price': 9000000,
        'sku': 'HP-OMEN-15GA0005TX',
        'stock_quantity': 3,
        'is_active': True,
        'category_slug': 'laptops',
        'images': [{'url': '/products/4.webp', 'alt_text': 'HP HyperX OMEN 15-ga0005TX Gaming', 'position': 0}],
    },
    {
        'name': 'Lenovo ThinkCentre Neo 50a Gen 6 24" All-in-One',
        'slug': 'lenovo-thinkcentre-neo-50a-gen-6-24-all-in-one',
        'description': '24-inch all-in-one desktop PC, Gen 6.',
        'price': 5000000,
        'compare_at_price': 5500000,
        'sku': 'LEN-TCN50A-G6-24A',
        'stock_quantity': 6,
        'is_active': True,
        'category_slug': 'desktops',
        'images': [{'url': '/products/lenovo-thinkcentre-neo-50a-gen-6-24-all-in-one.jpg', 'alt_text': 'Lenovo ThinkCentre Neo 50a Gen 6 24" All-in-One', 'position': 0}],
    },
    {
        'name': 'Lenovo ThinkCentre Neo 50a Gen 6 27" All-in-One',
        'slug': 'lenovo-thinkcentre-neo-50a-gen-6-27-all-in-one',
        'description': '27-inch all-in-one desktop PC, Gen 6.',
        'price': 4800000,
        'compare_at_price': 5000000,
        'sku': 'LEN-TCN50A-G6-27A',
        'stock_quantity': 5,
        'is_active': True,
        'category_slug': 'desktops',
        'images': [{'url': '/products/lenovo-thinkcentre-neo-50a-gen-6-27-all-in-one.jpg', 'alt_text': 'Lenovo ThinkCentre Neo 50a Gen 6 27" All-in-One', 'position': 0}],
    },
    {
        'name': 'HP Laptop 15-fd1126nia Intel Core Ultra 5 125H',
        'slug': 'hp-laptop-15-fd1126nia-intel-core-ultra-5-125h',
        'description': '15-inch laptop, Intel Core Ultra 5 125H.',
        'price': 3104000,
        'compare_at_price': 3200000,
        'sku': 'HP-15FD1126NIA',
        'stock_quantity': 10,
        'is_active': True,
        'category_slug': 'laptops',
        'images': [{'url': '/products/owner-2.jpg', 'alt_text': 'HP Laptop 15-fd1126nia Intel Core Ultra 5 125H', 'position': 0}],
    },
    {
        'name': 'Lenovo ThinkCentre Neo 50t Gen 6 Desktop - Intel',
        'slug': 'lenovo-thinkcentre-neo-50t-gen-6-desktop-intel',
        'description': 'Tower desktop PC, Gen 6, Intel.',
        'price': 3570000,
        'compare_at_price': 3800000,
        'sku': 'LEN-TCN50T-G6',
        'stock_quantity': 6,
        'is_active': True,
        'category_slug': 'desktops',
        'images': [{'url': '/products/lenovo-thinkcentre-neo-50t-gen-6-desktop-intel.jpg', 'alt_text': 'Lenovo ThinkCentre Neo 50t Gen 6 Desktop - Intel', 'position': 0}],
    },
    {
        'name': 'Dell Pro Tower Essential QVT1260 Desktop PC',
        'slug': 'dell-pro-tower-essential-qvt1260-desktop-pc',
        'description': 'Tower desktop PC.',
        'price': 3485000,
        'compare_at_price': 3800000,
        'sku': 'DELL-QVT1260-A',
        'stock_quantity': 7,
        'is_active': True,
        'category_slug': 'desktops',
        'images': [{'url': '/products/dell-pro-tower-essential-qvt1260-desktop-pc.jpg', 'alt_text': 'Dell Pro Tower Essential QVT1260 Desktop PC', 'position': 0}],
    },
    {
        'name': 'Dell Pro Tower Essential QVT1260 Desktop PC (B)',
        'slug': 'dell-pro-tower-essential-qvt1260-desktop-pc-b',
        'description': 'Tower desktop PC.',
        'price': 3194000,
        'compare_at_price': 3500000,
        'sku': 'DELL-QVT1260-B',
        'stock_quantity': 7,
        'is_active': True,
        'category_slug': 'desktops',
        'images': [{'url': '/products/dell-pro-tower-essential-qvt1260-desktop-pc-b.jpg', 'alt_text': 'Dell Pro Tower Essential QVT1260 Desktop PC (B)', 'position': 0}],
    },
    {
        'name': 'Dell Pro 15 PV15250 Laptop | Intel Core 3',
        'slug': 'dell-pro-15-pv15250-laptop-intel-core-3',
        'description': '15-inch laptop, Intel Core 3.',
        'price': 2342000,
        'compare_at_price': 2400000,
        'sku': 'DELL-PV15250',
        'stock_quantity': 9,
        'is_active': True,
        'category_slug': 'laptops',
        'images': [{'url': '/products/owner-1.jpg', 'alt_text': 'Dell Pro 15 PV15250 Laptop | Intel Core 3', 'position': 0}],
    },
    {
        'name': 'Lenovo IdeaPad Slim 3 14AMN8 14" FHD Laptop',
        'slug': 'lenovo-ideapad-slim-3-14amn8-14-fhd-laptop',
        'description': '14-inch FHD everyday laptop.',
        'price': 2185000,
        'compare_at_price': 2500000,
        'sku': 'LEN-IPS3-14AMN8-FHD',
        'stock_quantity': 10,
        'is_active': True,
        'category_slug': 'laptops',
        'images': [{'url': '/products/lenovo-ideapad-slim-3-14amn8-14-fhd-laptop.jpg', 'alt_text': 'Lenovo IdeaPad Slim 3 14AMN8 14" FHD Laptop', 'position': 0}],
    },
    {
        'name': 'ASUS TUF Gaming Wi-Fi Router',
        'slug': 'asus-tuf-gaming-wi-fi-router',
        'description': 'High-performance dual-band Wi-Fi router with multiple external antennas for wide coverage.',
        'price': 320000,
        'compare_at_price': None,
        'sku': 'ASUS-TUF-ROUTER',
        'stock_quantity': 10,
        'is_active': True,
        'category_slug': 'networking',
        'images': [{'url': '/products/asus-tuf-gaming-wi-fi-router.jpg', 'alt_text': 'ASUS TUF Gaming Wi-Fi Router', 'position': 0}],
    },
    {
        'name': 'CCTV Installation Service (Per Camera)',
        'slug': 'cctv-installation-service-per-camera',
        'description': 'Professional installation, cable routing, and setup for one CCTV camera, including basic configuration and mobile app connection.',
        'price': 50000,
        'compare_at_price': None,
        'sku': 'SVC-CCTV-INSTALL',
        'stock_quantity': 999,
        'is_active': True,
        'category_slug': 'installation-services',
        'images': [{'url': '/products/cctv-installation-service-per-camera.jpg', 'alt_text': 'CCTV Installation Service (Per Camera)', 'position': 0}],
    },
    {
        'name': 'GPS Tracker Installation & Activation',
        'slug': 'gps-tracker-installation-activation',
        'description': 'Professional fitting of a vehicle or asset GPS tracker, SIM activation, and mobile app setup.',
        'price': 30000,
        'compare_at_price': None,
        'sku': 'SVC-GPS-INSTALL',
        'stock_quantity': 999,
        'is_active': True,
        'category_slug': 'installation-services',
        'images': [{'url': '/products/gps-tracker-installation-activation.jpg', 'alt_text': 'GPS Tracker Installation & Activation', 'position': 0}],
    },
    {
        'name': 'Laptop/Computer Setup & Software Installation',
        'slug': 'laptop-computer-setup-software-installation',
        'description': 'Operating system setup, essential software installation, and data transfer for a new laptop or desktop.',
        'price': 25000,
        'compare_at_price': None,
        'sku': 'SVC-PC-SETUP',
        'stock_quantity': 999,
        'is_active': True,
        'category_slug': 'installation-services',
        'images': [{'url': '/products/laptop-computer-setup-software-installation.jpg', 'alt_text': 'Laptop/Computer Setup & Software Installation', 'position': 0}],
    },
    {
        'name': 'Home/Office Wi-Fi Network Setup',
        'slug': 'home-office-wi-fi-network-setup',
        'description': 'Router installation, Wi-Fi configuration, and network optimization for your home or office.',
        'price': 80000,
        'compare_at_price': None,
        'sku': 'SVC-NETWORK-SETUP',
        'stock_quantity': 999,
        'is_active': True,
        'category_slug': 'installation-services',
        'images': [{'url': '/products/home-office-wi-fi-network-setup.jpg', 'alt_text': 'Home/Office Wi-Fi Network Setup', 'position': 0}],
    },
    {
        'name': 'Dell 24" P2422H Full HD IPS Monitor',
        'slug': 'dell-24-p2422h-full-hd-ips-monitor',
        'description': '24-inch 1920x1080 IPS, height-adjustable stand, HDMI + DisplayPort.',
        'price': 720000,
        'compare_at_price': 820000,
        'sku': 'MON-DEL-P2422H',
        'stock_quantity': 9,
        'is_active': True,
        'category_slug': 'monitors',
        'images': [{'url': '/products/dell-24-p2422h-full-hd-ips-monitor.png', 'alt_text': 'Dell 24" P2422H Full HD IPS Monitor', 'position': 0}],
    },
    {
        'name': 'HP V24i 23.8" IPS Monitor',
        'slug': 'hp-v24i-23-8-ips-monitor',
        'description': '23.8-inch Full HD IPS, 75Hz, thin bezels for dual-screen setups.',
        'price': 610000,
        'compare_at_price': None,
        'sku': 'MON-HP-V24I',
        'stock_quantity': 12,
        'is_active': True,
        'category_slug': 'monitors',
        'images': [{'url': '/products/hp-v24i-23-8-ips-monitor.jpg', 'alt_text': 'HP V24i 23.8" IPS Monitor', 'position': 0}],
    },
    {
        'name': 'Samsung 27" Curved CF396 Monitor',
        'slug': 'samsung-27-curved-cf396-monitor',
        'description': '27-inch curved VA panel, 4ms response, AMD FreeSync.',
        'price': 890000,
        'compare_at_price': 980000,
        'sku': 'MON-SAM-CF396',
        'stock_quantity': 6,
        'is_active': True,
        'category_slug': 'monitors',
        'images': [{'url': '/products/samsung-27-curved-cf396-monitor.jpg', 'alt_text': 'Samsung 27" Curved CF396 Monitor', 'position': 0}],
    },
    {
        'name': 'LG 22MK400H 21.5" Gaming Monitor',
        'slug': 'lg-22mk400h-21-5-gaming-monitor',
        'description': '21.5-inch Full HD TN, 75Hz, 1ms motion blur reduction.',
        'price': 480000,
        'compare_at_price': None,
        'sku': 'MON-LG-22MK400',
        'stock_quantity': 14,
        'is_active': True,
        'category_slug': 'monitors',
        'images': [{'url': '/products/lg-22mk400h-21-5-gaming-monitor.jpg', 'alt_text': 'LG 22MK400H 21.5" Gaming Monitor', 'position': 0}],
    },
    {
        'name': 'Dell UltraSharp U2723QE 27" 4K',
        'slug': 'dell-ultrasharp-u2723qe-27-4k',
        'description': '27-inch 4K IPS Black, USB-C 90W power delivery, built-in hub.',
        'price': 2450000,
        'compare_at_price': 2700000,
        'sku': 'MON-DEL-U2723QE',
        'stock_quantity': 4,
        'is_active': True,
        'category_slug': 'monitors',
        'images': [{'url': '/products/dell-ultrasharp-u2723qe-27-4k.png', 'alt_text': 'Dell UltraSharp U2723QE 27" 4K', 'position': 0}],
    },
    {
        'name': 'HP E27 G5 27" QHD Monitor',
        'slug': 'hp-e27-g5-27-qhd-monitor',
        'description': '27-inch 2560x1440, USB-C docking, pivot and height adjust.',
        'price': 1350000,
        'compare_at_price': None,
        'sku': 'MON-HP-E27G5',
        'stock_quantity': 7,
        'is_active': True,
        'category_slug': 'monitors',
        'images': [{'url': '/products/hp-e27-g5-27-qhd-monitor.jpg', 'alt_text': 'HP E27 G5 27" QHD Monitor', 'position': 0}],
    },
    {
        'name': 'HP LaserJet Pro M404dn Printer',
        'slug': 'hp-laserjet-pro-m404dn-printer',
        'description': '38ppm mono laser, automatic duplex, Ethernet. Built for busy offices.',
        'price': 1580000,
        'compare_at_price': 1750000,
        'sku': 'PRN-HP-M404DN',
        'stock_quantity': 8,
        'is_active': True,
        'category_slug': 'printers',
        'images': [{'url': '/products/hp-laserjet-pro-m404dn-printer.jpg', 'alt_text': 'HP LaserJet Pro M404dn Printer', 'position': 0}],
    },
    {
        'name': 'Epson EcoTank L3250 All-in-One',
        'slug': 'epson-ecotank-l3250-all-in-one',
        'description': 'Print, scan and copy with refillable ink tanks. Wi-Fi Direct.',
        'price': 890000,
        'compare_at_price': None,
        'sku': 'PRN-EPS-L3250',
        'stock_quantity': 15,
        'is_active': True,
        'category_slug': 'printers',
        'images': [{'url': '/products/epson-ecotank-l3250-all-in-one.jpg', 'alt_text': 'Epson EcoTank L3250 All-in-One', 'position': 0}],
    },
    {
        'name': 'Canon PIXMA G3420 Ink Tank Printer',
        'slug': 'canon-pixma-g3420-ink-tank-printer',
        'description': 'Wireless all-in-one with high-yield ink tanks. Low cost per page.',
        'price': 760000,
        'compare_at_price': 840000,
        'sku': 'PRN-CAN-G3420',
        'stock_quantity': 11,
        'is_active': True,
        'category_slug': 'printers',
        'images': [{'url': '/products/canon-pixma-g3420-ink-tank-printer.jpg', 'alt_text': 'Canon PIXMA G3420 Ink Tank Printer', 'position': 0}],
    },
    {
        'name': 'HP LaserJet MFP M141a',
        'slug': 'hp-laserjet-mfp-m141a',
        'description': 'Compact mono laser multifunction: print, scan, copy.',
        'price': 720000,
        'compare_at_price': None,
        'sku': 'PRN-HP-M141A',
        'stock_quantity': 13,
        'is_active': True,
        'category_slug': 'printers',
        'images': [{'url': 'https://placehold.co/800x800/0f766e/ffffff.png?text=HP+LaserJet+MFP+M141a&font=roboto', 'alt_text': 'HP LaserJet MFP M141a', 'position': 0}],
    },
    {
        'name': 'Brother HL-L2350DW Wireless Laser',
        'slug': 'brother-hl-l2350dw-wireless-laser',
        'description': '32ppm mono laser with wireless and automatic duplex.',
        'price': 980000,
        'compare_at_price': 1080000,
        'sku': 'PRN-BRO-L2350DW',
        'stock_quantity': 6,
        'is_active': True,
        'category_slug': 'printers',
        'images': [{'url': '/products/brother-hl-l2350dw-wireless-laser.jpg', 'alt_text': 'Brother HL-L2350DW Wireless Laser', 'position': 0}],
    },
    {
        'name': 'Epson L3110 All-in-One Ink Tank',
        'slug': 'epson-l3110-all-in-one-ink-tank',
        'description': 'Entry-level tank printer for home and small office.',
        'price': 640000,
        'compare_at_price': None,
        'sku': 'PRN-EPS-L3110',
        'stock_quantity': 18,
        'is_active': True,
        'category_slug': 'printers',
        'images': [{'url': '/products/epson-l3110-all-in-one-ink-tank.jpg', 'alt_text': 'Epson L3110 All-in-One Ink Tank', 'position': 0}],
    },
    {
        'name': 'Canon CanoScan LiDE 300 Flatbed',
        'slug': 'canon-canoscan-lide-300-flatbed',
        'description': 'A4 flatbed scanner, 4800dpi, USB powered - no separate adapter.',
        'price': 420000,
        'compare_at_price': None,
        'sku': 'SCN-CAN-LIDE300',
        'stock_quantity': 10,
        'is_active': True,
        'category_slug': 'scanners',
        'images': [{'url': '/products/canon-canoscan-lide-300-flatbed.jpg', 'alt_text': 'Canon CanoScan LiDE 300 Flatbed', 'position': 0}],
    },
    {
        'name': 'Epson Perfection V39 Scanner',
        'slug': 'epson-perfection-v39-scanner',
        'description': 'A4 flatbed with 4800dpi and one-touch scan-to-PDF.',
        'price': 490000,
        'compare_at_price': 540000,
        'sku': 'SCN-EPS-V39',
        'stock_quantity': 8,
        'is_active': True,
        'category_slug': 'scanners',
        'images': [{'url': '/products/epson-perfection-v39-scanner.jpg', 'alt_text': 'Epson Perfection V39 Scanner', 'position': 0}],
    },
    {
        'name': 'Fujitsu ScanSnap iX1400 Document Scanner',
        'slug': 'fujitsu-scansnap-ix1400-document-scanner',
        'description': '40ppm duplex sheet-fed scanner for bulk paperwork.',
        'price': 2100000,
        'compare_at_price': None,
        'sku': 'SCN-FUJ-IX1400',
        'stock_quantity': 3,
        'is_active': True,
        'category_slug': 'scanners',
        'images': [{'url': '/products/fujitsu-scansnap-ix1400-document-scanner.jpg', 'alt_text': 'Fujitsu ScanSnap iX1400 Document Scanner', 'position': 0}],
    },
    {
        'name': 'HP ScanJet Pro 2000 s2 Sheet-feed',
        'slug': 'hp-scanjet-pro-2000-s2-sheet-feed',
        'description': '35ppm sheet-fed scanner with 50-page auto document feeder.',
        'price': 1450000,
        'compare_at_price': 1600000,
        'sku': 'SCN-HP-2000S2',
        'stock_quantity': 5,
        'is_active': True,
        'category_slug': 'scanners',
        'images': [{'url': '/products/hp-scanjet-pro-2000-s2-sheet-feed.jpg', 'alt_text': 'HP ScanJet Pro 2000 s2 Sheet-feed', 'position': 0}],
    },
    {
        'name': 'Canon DR-C225 II Document Scanner',
        'slug': 'canon-dr-c225-ii-document-scanner',
        'description': 'Compact duplex scanner with upright paper path, 25ppm.',
        'price': 1850000,
        'compare_at_price': None,
        'sku': 'SCN-CAN-DRC225',
        'stock_quantity': 4,
        'is_active': True,
        'category_slug': 'scanners',
        'images': [{'url': '/products/canon-dr-c225-ii-document-scanner.jpg', 'alt_text': 'Canon DR-C225 II Document Scanner', 'position': 0}],
    },
    {
        'name': 'Epson EB-S41 SVGA 3LCD Projector',
        'slug': 'epson-eb-s41-svga-3lcd-projector',
        'description': '3300 lumens, SVGA, HDMI. Bright enough for a lit classroom.',
        'price': 1750000,
        'compare_at_price': 1950000,
        'sku': 'PRJ-EPS-EBS41',
        'stock_quantity': 6,
        'is_active': True,
        'category_slug': 'projectors',
        'images': [{'url': '/products/epson-eb-s41-svga-3lcd-projector.jpg', 'alt_text': 'Epson EB-S41 SVGA 3LCD Projector', 'position': 0}],
    },
    {
        'name': 'BenQ MS550 SVGA Business Projector',
        'slug': 'benq-ms550-svga-business-projector',
        'description': '3600 lumens, 20000:1 contrast, 15000-hour lamp in eco mode.',
        'price': 1620000,
        'compare_at_price': None,
        'sku': 'PRJ-BENQ-MS550',
        'stock_quantity': 7,
        'is_active': True,
        'category_slug': 'projectors',
        'images': [{'url': '/products/benq-ms550-svga-business-projector.jpg', 'alt_text': 'BenQ MS550 SVGA Business Projector', 'position': 0}],
    },
    {
        'name': 'Epson EB-X51 XGA 3LCD Projector',
        'slug': 'epson-eb-x51-xga-3lcd-projector',
        'description': '3800 lumens XGA with HDMI and USB display.',
        'price': 2280000,
        'compare_at_price': 2500000,
        'sku': 'PRJ-EPS-EBX51',
        'stock_quantity': 5,
        'is_active': True,
        'category_slug': 'projectors',
        'images': [{'url': 'https://placehold.co/800x800/0f766e/ffffff.png?text=Epson+EB-X51+XGA+3LCD+Projector&font=roboto', 'alt_text': 'Epson EB-X51 XGA 3LCD Projector', 'position': 0}],
    },
    {
        'name': 'ViewSonic PA503S Portable Projector',
        'slug': 'viewsonic-pa503s-portable-projector',
        'description': '3800 lumens SVGA, dual HDMI, quick-off for fast pack-down.',
        'price': 1490000,
        'compare_at_price': None,
        'sku': 'PRJ-VS-PA503S',
        'stock_quantity': 9,
        'is_active': True,
        'category_slug': 'projectors',
        'images': [{'url': '/products/viewsonic-pa503s-portable-projector.jpg', 'alt_text': 'ViewSonic PA503S Portable Projector', 'position': 0}],
    },
    {
        'name': 'Portable Mini LED Projector 1080p',
        'slug': 'portable-mini-led-projector-1080p',
        'description': 'Compact 1080p-supported LED projector with HDMI and USB.',
        'price': 520000,
        'compare_at_price': 620000,
        'sku': 'PRJ-MINI-LED',
        'stock_quantity': 16,
        'is_active': True,
        'category_slug': 'projectors',
        'images': [{'url': '/products/portable-mini-led-projector-1080p.jpg', 'alt_text': 'Portable Mini LED Projector 1080p', 'position': 0}],
    },
    {
        'name': 'APC Back-UPS BX650LI 650VA',
        'slug': 'apc-back-ups-bx650li-650va',
        'description': '650VA/325W line-interactive UPS with AVR. Keeps a desktop alive through a cut.',
        'price': 480000,
        'compare_at_price': 540000,
        'sku': 'UPS-APC-BX650',
        'stock_quantity': 14,
        'is_active': True,
        'category_slug': 'ups',
        'images': [{'url': '/products/apc-back-ups-bx650li-650va.jpg', 'alt_text': 'APC Back-UPS BX650LI 650VA', 'position': 0}],
    },
    {
        'name': 'APC Back-UPS BX1100LI 1100VA',
        'slug': 'apc-back-ups-bx1100li-1100va',
        'description': '1100VA/550W with AVR and six outlets. Suits a workstation plus monitor.',
        'price': 850000,
        'compare_at_price': None,
        'sku': 'UPS-APC-BX1100',
        'stock_quantity': 9,
        'is_active': True,
        'category_slug': 'ups',
        'images': [{'url': '/products/apc-back-ups-bx1100li-1100va.jpg', 'alt_text': 'APC Back-UPS BX1100LI 1100VA', 'position': 0}],
    },
    {
        'name': 'Mercury Elite 1000VA UPS',
        'slug': 'mercury-elite-1000va-ups',
        'description': '1000VA offline UPS with surge protection and 4 outlets.',
        'price': 420000,
        'compare_at_price': 470000,
        'sku': 'UPS-MER-EL1000',
        'stock_quantity': 12,
        'is_active': True,
        'category_slug': 'ups',
        'images': [{'url': '/products/mercury-elite-1000va-ups.jpg', 'alt_text': 'Mercury Elite 1000VA UPS', 'position': 0}],
    },
    {
        'name': 'APC Smart-UPS 1500VA LCD',
        'slug': 'apc-smart-ups-1500va-lcd',
        'description': '1500VA/1000W sine-wave UPS with LCD status and network card slot.',
        'price': 3200000,
        'compare_at_price': None,
        'sku': 'UPS-APC-SMT1500',
        'stock_quantity': 3,
        'is_active': True,
        'category_slug': 'ups',
        'images': [{'url': '/products/apc-smart-ups-1500va-lcd.jpg', 'alt_text': 'APC Smart-UPS 1500VA LCD', 'position': 0}],
    },
    {
        'name': 'Mercury 650VA Line-Interactive UPS',
        'slug': 'mercury-650va-line-interactive-ups',
        'description': 'Entry UPS for a single PC or till point.',
        'price': 290000,
        'compare_at_price': None,
        'sku': 'UPS-MER-650',
        'stock_quantity': 20,
        'is_active': True,
        'category_slug': 'ups',
        'images': [{'url': '/products/mercury-650va-line-interactive-ups.jpg', 'alt_text': 'Mercury 650VA Line-Interactive UPS', 'position': 0}],
    },
    {
        'name': 'HP 117A Black Original Toner',
        'slug': 'hp-117a-black-original-toner',
        'description': 'Genuine HP 117A black cartridge, approx. 1000 pages.',
        'price': 185000,
        'compare_at_price': None,
        'sku': 'TNR-HP-117A-BK',
        'stock_quantity': 30,
        'is_active': True,
        'category_slug': 'toner-ink',
        'images': [{'url': '/products/hp-117a-black-original-toner.jpg', 'alt_text': 'HP 117A Black Original Toner', 'position': 0}],
    },
    {
        'name': 'HP 117A Colour Toner Set (C/M/Y)',
        'slug': 'hp-117a-colour-toner-set-c-m-y',
        'description': 'Cyan, magenta and yellow set for HP Color Laser 150/178.',
        'price': 520000,
        'compare_at_price': 580000,
        'sku': 'TNR-HP-117A-CMY',
        'stock_quantity': 12,
        'is_active': True,
        'category_slug': 'toner-ink',
        'images': [{'url': '/products/hp-117a-colour-toner-set-c-m-y.jpg', 'alt_text': 'HP 117A Colour Toner Set (C/M/Y)', 'position': 0}],
    },
    {
        'name': 'Canon 047 Black Toner Cartridge',
        'slug': 'canon-047-black-toner-cartridge',
        'description': 'Genuine Canon 047, approx. 1600 pages for LBP112/MF113.',
        'price': 210000,
        'compare_at_price': None,
        'sku': 'TNR-CAN-047',
        'stock_quantity': 18,
        'is_active': True,
        'category_slug': 'toner-ink',
        'images': [{'url': '/products/canon-047-black-toner-cartridge.jpg', 'alt_text': 'Canon 047 Black Toner Cartridge', 'position': 0}],
    },
    {
        'name': 'Epson 003 Ink Bottle Black 65ml',
        'slug': 'epson-003-ink-bottle-black-65ml',
        'description': 'Genuine Epson 003 black ink for L3110/L3150/L3250 tanks.',
        'price': 38000,
        'compare_at_price': 45000,
        'sku': 'INK-EPS-003-BK',
        'stock_quantity': 60,
        'is_active': True,
        'category_slug': 'toner-ink',
        'images': [{'url': '/products/epson-003-ink-bottle-black-65ml.jpg', 'alt_text': 'Epson 003 Ink Bottle Black 65ml', 'position': 0}],
    },
    {
        'name': 'Epson 003 Ink Bottle Set (C/M/Y)',
        'slug': 'epson-003-ink-bottle-set-c-m-y',
        'description': 'Cyan, magenta and yellow 65ml bottles for EcoTank printers.',
        'price': 105000,
        'compare_at_price': None,
        'sku': 'INK-EPS-003-CMY',
        'stock_quantity': 40,
        'is_active': True,
        'category_slug': 'toner-ink',
        'images': [{'url': '/products/epson-003-ink-bottle-set-c-m-y.jpg', 'alt_text': 'Epson 003 Ink Bottle Set (C/M/Y)', 'position': 0}],
    },
    {
        'name': 'HP 682 Tri-colour Ink Cartridge',
        'slug': 'hp-682-tri-colour-ink-cartridge',
        'description': 'Genuine HP 682 tri-colour for DeskJet Ink Advantage.',
        'price': 62000,
        'compare_at_price': 72000,
        'sku': 'INK-HP-682-TRI',
        'stock_quantity': 25,
        'is_active': True,
        'category_slug': 'toner-ink',
        'images': [{'url': '/products/hp-682-tri-colour-ink-cartridge.jpg', 'alt_text': 'HP 682 Tri-colour Ink Cartridge', 'position': 0}],
    },
    {
        'name': 'Glory GFB-800 Banknote Counter',
        'slug': 'glory-gfb-800-banknote-counter',
        'description': 'Counts up to 1000 notes/min with UV and MG counterfeit detection.',
        'price': 2850000,
        'compare_at_price': 3200000,
        'sku': 'MCM-GLO-GFB800',
        'stock_quantity': 4,
        'is_active': True,
        'category_slug': 'money-counting-machines',
        'images': [{'url': '/products/glory-gfb-800-banknote-counter.jpg', 'alt_text': 'Glory GFB-800 Banknote Counter', 'position': 0}],
    },
    {
        'name': 'Nadle NC-6300 Money Counter',
        'slug': 'nadle-nc-6300-money-counter',
        'description': 'Mixed-denomination counting with value totals and fake-note alerts.',
        'price': 1650000,
        'compare_at_price': None,
        'sku': 'MCM-NAD-NC6300',
        'stock_quantity': 7,
        'is_active': True,
        'category_slug': 'money-counting-machines',
        'images': [{'url': '/products/nadle-nc-6300-money-counter.jpg', 'alt_text': 'Nadle NC-6300 Money Counter', 'position': 0}],
    },
    {
        'name': 'Bill Counter BC-2020 with UV/MG',
        'slug': 'bill-counter-bc-2020-with-uv-mg',
        'description': 'Reliable desktop note counter with batch and add modes.',
        'price': 890000,
        'compare_at_price': 990000,
        'sku': 'MCM-BC-2020',
        'stock_quantity': 10,
        'is_active': True,
        'category_slug': 'money-counting-machines',
        'images': [{'url': '/products/bill-counter-bc-2020-with-uv-mg.jpg', 'alt_text': 'Bill Counter BC-2020 with UV/MG', 'position': 0}],
    },
    {
        'name': 'Cassida 5520 UV Bill Counter',
        'slug': 'cassida-5520-uv-bill-counter',
        'description': '1300 notes/min, ultraviolet and dimension counterfeit checks.',
        'price': 1420000,
        'compare_at_price': None,
        'sku': 'MCM-CAS-5520',
        'stock_quantity': 6,
        'is_active': True,
        'category_slug': 'money-counting-machines',
        'images': [{'url': 'https://placehold.co/800x800/0f766e/ffffff.png?text=Cassida+5520+UV+Bill+Counter&font=roboto', 'alt_text': 'Cassida 5520 UV Bill Counter', 'position': 0}],
    },
    {
        'name': 'Portable Mini Note Counter MC-100',
        'slug': 'portable-mini-note-counter-mc-100',
        'description': 'Compact counter for market stalls and small shops.',
        'price': 320000,
        'compare_at_price': 380000,
        'sku': 'MCM-MC100',
        'stock_quantity': 15,
        'is_active': True,
        'category_slug': 'money-counting-machines',
        'images': [{'url': 'https://placehold.co/800x800/0f766e/ffffff.png?text=Portable+Mini+Note+Counter+MC-100&font=roboto', 'alt_text': 'Portable Mini Note Counter MC-100', 'position': 0}],
    },
    {
        'name': 'Fellowes Powershred 8Cd Cross-Cut',
        'slug': 'fellowes-powershred-8cd-cross-cut',
        'description': '8-sheet cross-cut shredder, also handles cards and CDs. P-4 security.',
        'price': 720000,
        'compare_at_price': 820000,
        'sku': 'SHR-FEL-8CD',
        'stock_quantity': 8,
        'is_active': True,
        'category_slug': 'paper-shredders',
        'images': [{'url': '/products/fellowes-powershred-8cd-cross-cut.jpg', 'alt_text': 'Fellowes Powershred 8Cd Cross-Cut', 'position': 0}],
    },
    {
        'name': 'Bosch AZ-1200 Strip-Cut Shredder',
        'slug': 'bosch-az-1200-strip-cut-shredder',
        'description': '12-sheet strip-cut with 20-litre bin for steady office use.',
        'price': 560000,
        'compare_at_price': None,
        'sku': 'SHR-BOS-AZ1200',
        'stock_quantity': 10,
        'is_active': True,
        'category_slug': 'paper-shredders',
        'images': [{'url': '/products/bosch-az-1200-strip-cut-shredder.jpg', 'alt_text': 'Bosch AZ-1200 Strip-Cut Shredder', 'position': 0}],
    },
    {
        'name': 'Ativa 12-Sheet Micro-Cut Shredder',
        'slug': 'ativa-12-sheet-micro-cut-shredder',
        'description': 'P-5 micro-cut for confidential paperwork, 21-litre bin.',
        'price': 1150000,
        'compare_at_price': 1290000,
        'sku': 'SHR-ATI-12MC',
        'stock_quantity': 5,
        'is_active': True,
        'category_slug': 'paper-shredders',
        'images': [{'url': 'https://placehold.co/800x800/0f766e/ffffff.png?text=Ativa+12-Sheet+Micro-Cut+Shredder&font=roboto', 'alt_text': 'Ativa 12-Sheet Micro-Cut Shredder', 'position': 0}],
    },
    {
        'name': 'Rexel Momentum X410 Shredder',
        'slug': 'rexel-momentum-x410-shredder',
        'description': '10-sheet cross-cut, jam-free technology, 23-litre bin.',
        'price': 980000,
        'compare_at_price': None,
        'sku': 'SHR-REX-X410',
        'stock_quantity': 6,
        'is_active': True,
        'category_slug': 'paper-shredders',
        'images': [{'url': 'https://placehold.co/800x800/0f766e/ffffff.png?text=Rexel+Momentum+X410+Shredder&font=roboto', 'alt_text': 'Rexel Momentum X410 Shredder', 'position': 0}],
    },
    {
        'name': 'Compact Home Shredder 6-Sheet',
        'slug': 'compact-home-shredder-6-sheet',
        'description': 'Small cross-cut shredder for home office desks.',
        'price': 320000,
        'compare_at_price': 380000,
        'sku': 'SHR-HOME-6',
        'stock_quantity': 14,
        'is_active': True,
        'category_slug': 'paper-shredders',
        'images': [{'url': '/products/compact-home-shredder-6-sheet.jpg', 'alt_text': 'Compact Home Shredder 6-Sheet', 'position': 0}],
    },
    {
        'name': 'Samsung HW-B450 2.1ch Soundbar',
        'slug': 'samsung-hw-b450-2-1ch-soundbar',
        'description': '300W 2.1 channel soundbar with wireless subwoofer and Bluetooth.',
        'price': 1250000,
        'compare_at_price': 1420000,
        'sku': 'SB-SAM-HWB450',
        'stock_quantity': 8,
        'is_active': True,
        'category_slug': 'sound-bars',
        'images': [{'url': '/products/samsung-hw-b450-2-1ch-soundbar.jpg', 'alt_text': 'Samsung HW-B450 2.1ch Soundbar', 'position': 0}],
    },
    {
        'name': 'JBL Bar 2.0 All-in-One Soundbar',
        'slug': 'jbl-bar-2-0-all-in-one-soundbar',
        'description': '80W compact soundbar with built-in bass and HDMI ARC.',
        'price': 980000,
        'compare_at_price': None,
        'sku': 'SB-JBL-BAR20',
        'stock_quantity': 11,
        'is_active': True,
        'category_slug': 'sound-bars',
        'images': [{'url': '/products/jbl-bar-2-0-all-in-one-soundbar.jpg', 'alt_text': 'JBL Bar 2.0 All-in-One Soundbar', 'position': 0}],
    },
    {
        'name': 'LG SN4 2.1ch Soundbar with Subwoofer',
        'slug': 'lg-sn4-2-1ch-soundbar-with-subwoofer',
        'description': '300W with DTS Virtual:X and wireless subwoofer.',
        'price': 1180000,
        'compare_at_price': 1300000,
        'sku': 'SB-LG-SN4',
        'stock_quantity': 7,
        'is_active': True,
        'category_slug': 'sound-bars',
        'images': [{'url': '/products/lg-sn4-2-1ch-soundbar-with-subwoofer.jpg', 'alt_text': 'LG SN4 2.1ch Soundbar with Subwoofer', 'position': 0}],
    },
    {
        'name': 'Sony HT-S400 2.1ch Soundbar',
        'slug': 'sony-ht-s400-2-1ch-soundbar',
        'description': '330W with X-Balanced speaker unit and powerful wireless sub.',
        'price': 1650000,
        'compare_at_price': None,
        'sku': 'SB-SONY-HTS400',
        'stock_quantity': 5,
        'is_active': True,
        'category_slug': 'sound-bars',
        'images': [{'url': '/products/sony-ht-s400-2-1ch-soundbar.jpg', 'alt_text': 'Sony HT-S400 2.1ch Soundbar', 'position': 0}],
    },
    {
        'name': 'Vitron Home Theatre Soundbar 2.1',
        'slug': 'vitron-home-theatre-soundbar-2-1',
        'description': 'Budget 2.1 soundbar with Bluetooth, USB and FM radio.',
        'price': 420000,
        'compare_at_price': 490000,
        'sku': 'SB-VIT-21',
        'stock_quantity': 16,
        'is_active': True,
        'category_slug': 'sound-bars',
        'images': [{'url': '/products/vitron-home-theatre-soundbar-2-1.jpg', 'alt_text': 'Vitron Home Theatre Soundbar 2.1', 'position': 0}],
    },
    {
        'name': 'Panasonic 25L Microwave Oven NN-ST34',
        'slug': 'panasonic-25l-microwave-oven-nn-st34',
        'description': '25-litre microwave with one-touch auto cook and child lock.',
        'price': 890000,
        'compare_at_price': 990000,
        'sku': 'HA-PAN-NNST34',
        'stock_quantity': 9,
        'is_active': True,
        'category_slug': 'home-appliances',
        'images': [{'url': '/products/panasonic-25l-microwave-oven-nn-st34.jpg', 'alt_text': 'Panasonic 25L Microwave Oven NN-ST34', 'position': 0}],
    },
    {
        'name': 'Ramtons 20L Solo Microwave',
        'slug': 'ramtons-20l-solo-microwave',
        'description': '20-litre solo microwave, 700W, six power levels.',
        'price': 480000,
        'compare_at_price': None,
        'sku': 'HA-RAM-20L',
        'stock_quantity': 14,
        'is_active': True,
        'category_slug': 'home-appliances',
        'images': [{'url': '/products/ramtons-20l-solo-microwave.jpg', 'alt_text': 'Ramtons 20L Solo Microwave', 'position': 0}],
    },
    {
        'name': 'Von 1.7L Cordless Electric Kettle',
        'slug': 'von-1-7l-cordless-electric-kettle',
        'description': 'Stainless steel kettle with auto shut-off and boil-dry protection.',
        'price': 95000,
        'compare_at_price': 120000,
        'sku': 'HA-VON-KETTLE',
        'stock_quantity': 30,
        'is_active': True,
        'category_slug': 'home-appliances',
        'images': [{'url': '/products/von-1-7l-cordless-electric-kettle.jpg', 'alt_text': 'Von 1.7L Cordless Electric Kettle', 'position': 0}],
    },
    {
        'name': 'Philips Daily Collection Blender HR2221',
        'slug': 'philips-daily-collection-blender-hr2221',
        'description': '600W blender with 2-litre jar and ProBlend crushing.',
        'price': 320000,
        'compare_at_price': None,
        'sku': 'HA-PHI-HR2221',
        'stock_quantity': 12,
        'is_active': True,
        'category_slug': 'home-appliances',
        'images': [{'url': 'https://placehold.co/800x800/0f766e/ffffff.png?text=Philips+Daily+Collection+Blender+HR2221&font=roboto', 'alt_text': 'Philips Daily Collection Blender HR2221', 'position': 0}],
    },
    {
        'name': 'Ramtons Dry Iron RM/188',
        'slug': 'ramtons-dry-iron-rm-188',
        'description': '1200W non-stick soleplate dry iron with adjustable thermostat.',
        'price': 78000,
        'compare_at_price': 95000,
        'sku': 'HA-RAM-IRON',
        'stock_quantity': 25,
        'is_active': True,
        'category_slug': 'home-appliances',
        'images': [{'url': 'https://placehold.co/800x800/0f766e/ffffff.png?text=Ramtons+Dry+Iron+RM%2F188&font=roboto', 'alt_text': 'Ramtons Dry Iron RM/188', 'position': 0}],
    },
    {
        'name': 'Nunix 2-Burner Table Top Gas Cooker',
        'slug': 'nunix-2-burner-table-top-gas-cooker',
        'description': 'Stainless steel two-burner cooker for compact kitchens.',
        'price': 185000,
        'compare_at_price': None,
        'sku': 'HA-NUN-2BURN',
        'stock_quantity': 18,
        'is_active': True,
        'category_slug': 'home-appliances',
        'images': [{'url': 'https://placehold.co/800x800/0f766e/ffffff.png?text=Nunix+2-Burner+Table+Top+Gas+Cooker&font=roboto', 'alt_text': 'Nunix 2-Burner Table Top Gas Cooker', 'position': 0}],
    },
    {
        'name': 'TP-Link TL-SG108 8-Port Gigabit Switch',
        'slug': 'tp-link-tl-sg108-8-port-gigabit-switch',
        'description': 'Unmanaged 8-port gigabit desktop switch, metal case, plug and play.',
        'price': 195000,
        'compare_at_price': 230000,
        'sku': 'NET-TPL-SG108',
        'stock_quantity': 20,
        'is_active': True,
        'category_slug': 'networking',
        'images': [{'url': '/products/tp-link-tl-sg108-8-port-gigabit-switch.jpg', 'alt_text': 'TP-Link TL-SG108 8-Port Gigabit Switch', 'position': 0}],
    },
    {
        'name': 'Netgear GS305 5-Port Gigabit Switch',
        'slug': 'netgear-gs305-5-port-gigabit-switch',
        'description': 'Compact 5-port gigabit switch with silent fanless operation.',
        'price': 150000,
        'compare_at_price': None,
        'sku': 'NET-NET-GS305',
        'stock_quantity': 22,
        'is_active': True,
        'category_slug': 'networking',
        'images': [{'url': '/products/netgear-gs305-5-port-gigabit-switch.jpg', 'alt_text': 'Netgear GS305 5-Port Gigabit Switch', 'position': 0}],
    },
    {
        'name': 'TP-Link Archer C6 AC1200 Router',
        'slug': 'tp-link-archer-c6-ac1200-router',
        'description': 'Dual-band gigabit Wi-Fi router with four external antennas.',
        'price': 285000,
        'compare_at_price': 330000,
        'sku': 'NET-TPL-C6',
        'stock_quantity': 16,
        'is_active': True,
        'category_slug': 'networking',
        'images': [{'url': '/products/tp-link-archer-c6-ac1200-router.jpg', 'alt_text': 'TP-Link Archer C6 AC1200 Router', 'position': 0}],
    },
    {
        'name': 'Mikrotik hAP ac lite Router',
        'slug': 'mikrotik-hap-ac-lite-router',
        'description': 'Dual-band router running RouterOS - the workhorse for small ISPs.',
        'price': 310000,
        'compare_at_price': None,
        'sku': 'NET-MKT-HAPACL',
        'stock_quantity': 12,
        'is_active': True,
        'category_slug': 'networking',
        'images': [{'url': '/products/mikrotik-hap-ac-lite-router.jpg', 'alt_text': 'Mikrotik hAP ac lite Router', 'position': 0}],
    },
    {
        'name': 'TP-Link TL-WA855RE Wi-Fi Extender',
        'slug': 'tp-link-tl-wa855re-wi-fi-extender',
        'description': '300Mbps range extender with pass-through socket.',
        'price': 110000,
        'compare_at_price': 135000,
        'sku': 'NET-TPL-WA855',
        'stock_quantity': 24,
        'is_active': True,
        'category_slug': 'networking',
        'images': [{'url': '/products/tp-link-tl-wa855re-wi-fi-extender.jpg', 'alt_text': 'TP-Link TL-WA855RE Wi-Fi Extender', 'position': 0}],
    },
    {
        'name': 'Cat6 Ethernet Cable 305m Box',
        'slug': 'cat6-ethernet-cable-305m-box',
        'description': 'Solid copper Cat6 UTP cable, 305-metre pull box for structured cabling.',
        'price': 620000,
        'compare_at_price': None,
        'sku': 'NET-CAT6-305',
        'stock_quantity': 8,
        'is_active': True,
        'category_slug': 'networking',
        'images': [{'url': '/products/cat6-ethernet-cable-305m-box.jpg', 'alt_text': 'Cat6 Ethernet Cable 305m Box', 'position': 0}],
    },
    {
        'name': 'JBL Flip 6 Portable Bluetooth Speaker',
        'slug': 'jbl-flip-6-portable-bluetooth-speaker',
        'description': 'IP67 waterproof, 12-hour battery, JBL Pro Sound.',
        'price': 620000,
        'compare_at_price': 720000,
        'sku': 'AUD-JBL-FLIP6',
        'stock_quantity': 12,
        'is_active': True,
        'category_slug': 'audio',
        'images': [{'url': '/products/jbl-flip-6-portable-bluetooth-speaker.jpg', 'alt_text': 'JBL Flip 6 Portable Bluetooth Speaker', 'position': 0}],
    },
    {
        'name': 'Anker Soundcore 2 Bluetooth Speaker',
        'slug': 'anker-soundcore-2-bluetooth-speaker',
        'description': '24-hour playtime, IPX7 waterproof, punchy bass.',
        'price': 220000,
        'compare_at_price': None,
        'sku': 'AUD-ANK-SC2',
        'stock_quantity': 20,
        'is_active': True,
        'category_slug': 'audio',
        'images': [{'url': '/products/anker-soundcore-2-bluetooth-speaker.jpg', 'alt_text': 'Anker Soundcore 2 Bluetooth Speaker', 'position': 0}],
    },
    {
        'name': 'Sony WH-CH520 Wireless Headphones',
        'slug': 'sony-wh-ch520-wireless-headphones',
        'description': '50-hour battery, multipoint connection, lightweight on-ear.',
        'price': 340000,
        'compare_at_price': 390000,
        'sku': 'AUD-SONY-CH520',
        'stock_quantity': 14,
        'is_active': True,
        'category_slug': 'audio',
        'images': [{'url': '/products/sony-wh-ch520-wireless-headphones.jpg', 'alt_text': 'Sony WH-CH520 Wireless Headphones', 'position': 0}],
    },
    {
        'name': 'JBL Tune 510BT Wireless Headphones',
        'slug': 'jbl-tune-510bt-wireless-headphones',
        'description': '40-hour battery with JBL Pure Bass and fast charge.',
        'price': 280000,
        'compare_at_price': None,
        'sku': 'AUD-JBL-510BT',
        'stock_quantity': 16,
        'is_active': True,
        'category_slug': 'audio',
        'images': [{'url': '/products/jbl-tune-510bt-wireless-headphones.jpg', 'alt_text': 'JBL Tune 510BT Wireless Headphones', 'position': 0}],
    },
    {
        'name': 'Oraimo FreePods 4 Earbuds',
        'slug': 'oraimo-freepods-4-earbuds',
        'description': 'ENC calling, 30-hour total playtime, low-latency game mode.',
        'price': 135000,
        'compare_at_price': 165000,
        'sku': 'AUD-ORA-FP4',
        'stock_quantity': 28,
        'is_active': True,
        'category_slug': 'audio',
        'images': [{'url': 'https://placehold.co/800x800/0f766e/ffffff.png?text=Oraimo+FreePods+4+Earbuds&font=roboto', 'alt_text': 'Oraimo FreePods 4 Earbuds', 'position': 0}],
    },
    {
        'name': 'Concox GT06N Vehicle GPS Tracker',
        'slug': 'concox-gt06n-vehicle-gps-tracker',
        'description': 'Real-time tracking with remote engine cut-off and SOS alert.',
        'price': 195000,
        'compare_at_price': 240000,
        'sku': 'GPS-CON-GT06N',
        'stock_quantity': 18,
        'is_active': True,
        'category_slug': 'gps-trackers',
        'images': [{'url': '/products/concox-gt06n-vehicle-gps-tracker.jpg', 'alt_text': 'Concox GT06N Vehicle GPS Tracker', 'position': 0}],
    },
    {
        'name': 'Coban TK103B Car Tracker',
        'slug': 'coban-tk103b-car-tracker',
        'description': 'Classic wired vehicle tracker with geo-fence and over-speed alerts.',
        'price': 165000,
        'compare_at_price': None,
        'sku': 'GPS-COB-TK103B',
        'stock_quantity': 15,
        'is_active': True,
        'category_slug': 'gps-trackers',
        'images': [{'url': '/products/coban-tk103b-car-tracker.png', 'alt_text': 'Coban TK103B Car Tracker', 'position': 0}],
    },
    {
        'name': 'Magnetic Asset Tracker GT710',
        'slug': 'magnetic-asset-tracker-gt710',
        'description': 'Battery-powered magnetic tracker, up to 90 days standby.',
        'price': 280000,
        'compare_at_price': 320000,
        'sku': 'GPS-GT710',
        'stock_quantity': 10,
        'is_active': True,
        'category_slug': 'gps-trackers',
        'images': [{'url': '/products/magnetic-asset-tracker-gt710.png', 'alt_text': 'Magnetic Asset Tracker GT710', 'position': 0}],
    },
    {
        'name': 'Mini Personal GPS Tracker MT-90',
        'slug': 'mini-personal-gps-tracker-mt-90',
        'description': 'Pocket tracker for luggage, children and field staff.',
        'price': 145000,
        'compare_at_price': None,
        'sku': 'GPS-MT90',
        'stock_quantity': 20,
        'is_active': True,
        'category_slug': 'gps-trackers',
        'images': [{'url': '/products/mini-personal-gps-tracker-mt-90.jpg', 'alt_text': 'Mini Personal GPS Tracker MT-90', 'position': 0}],
    },
    {
        'name': 'Oraimo 20000mAh Power Bank',
        'slug': 'oraimo-20000mah-power-bank',
        'description': '20000mAh with 20W PD fast charge and dual USB output.',
        'price': 165000,
        'compare_at_price': 195000,
        'sku': 'PA-ORA-PB20K',
        'stock_quantity': 25,
        'is_active': True,
        'category_slug': 'phone-accessories',
        'images': [{'url': '/products/oraimo-20000mah-power-bank.jpg', 'alt_text': 'Oraimo 20000mAh Power Bank', 'position': 0}],
    },
    {
        'name': 'Anker PowerPort 20W USB-C Charger',
        'slug': 'anker-powerport-20w-usb-c-charger',
        'description': 'Compact 20W USB-C PD wall charger for fast phone charging.',
        'price': 78000,
        'compare_at_price': None,
        'sku': 'PA-ANK-20W',
        'stock_quantity': 35,
        'is_active': True,
        'category_slug': 'phone-accessories',
        'images': [{'url': '/products/anker-powerport-20w-usb-c-charger.jpg', 'alt_text': 'Anker PowerPort 20W USB-C Charger', 'position': 0}],
    },
    {
        'name': 'Braided USB-C to Lightning Cable 2m',
        'slug': 'braided-usb-c-to-lightning-cable-2m',
        'description': 'MFi-style braided cable rated for 10000 bends.',
        'price': 45000,
        'compare_at_price': 58000,
        'sku': 'PA-CBL-CL2M',
        'stock_quantity': 50,
        'is_active': True,
        'category_slug': 'phone-accessories',
        'images': [{'url': '/products/braided-usb-c-to-lightning-cable-2m.jpg', 'alt_text': 'Braided USB-C to Lightning Cable 2m', 'position': 0}],
    },
    {
        'name': 'Universal Phone Ring Holder Stand',
        'slug': 'universal-phone-ring-holder-stand',
        'description': '360-degree metal ring grip and kickstand.',
        'price': 12000,
        'compare_at_price': None,
        'sku': 'PA-RING',
        'stock_quantity': 80,
        'is_active': True,
        'category_slug': 'phone-accessories',
        'images': [{'url': 'https://placehold.co/800x800/0f766e/ffffff.png?text=Universal+Phone+Ring+Holder+Stand&font=roboto', 'alt_text': 'Universal Phone Ring Holder Stand', 'position': 0}],
    },
    {
        'name': 'Tempered Glass Screen Protector',
        'slug': 'tempered-glass-screen-protector',
        'description': '9H tempered glass with oleophobic coating. Fits most 6.1-6.7" phones.',
        'price': 15000,
        'compare_at_price': 22000,
        'sku': 'PA-GLASS',
        'stock_quantity': 100,
        'is_active': True,
        'category_slug': 'phone-accessories',
        'images': [{'url': 'https://placehold.co/800x800/0f766e/ffffff.png?text=Tempered+Glass+Screen+Protector&font=roboto', 'alt_text': 'Tempered Glass Screen Protector', 'position': 0}],
    },
    {
        'name': 'SanDisk Ultra 64GB USB 3.0 Flash Drive',
        'slug': 'sandisk-ultra-64gb-usb-3-0-flash-drive',
        'description': '64GB USB 3.0 drive, up to 130MB/s read.',
        'price': 48000,
        'compare_at_price': 58000,
        'sku': 'CA-SAN-64GB',
        'stock_quantity': 45,
        'is_active': True,
        'category_slug': 'computer-accessories',
        'images': [{'url': '/products/sandisk-ultra-64gb-usb-3-0-flash-drive.jpg', 'alt_text': 'SanDisk Ultra 64GB USB 3.0 Flash Drive', 'position': 0}],
    },
    {
        'name': 'SanDisk Ultra 128GB USB 3.0 Flash Drive',
        'slug': 'sandisk-ultra-128gb-usb-3-0-flash-drive',
        'description': '128GB USB 3.0 drive for large project files.',
        'price': 82000,
        'compare_at_price': None,
        'sku': 'CA-SAN-128GB',
        'stock_quantity': 30,
        'is_active': True,
        'category_slug': 'computer-accessories',
        'images': [{'url': '/products/sandisk-ultra-128gb-usb-3-0-flash-drive.jpg', 'alt_text': 'SanDisk Ultra 128GB USB 3.0 Flash Drive', 'position': 0}],
    },
    {
        'name': 'Seagate 1TB Portable External HDD',
        'slug': 'seagate-1tb-portable-external-hdd',
        'description': 'USB 3.0 portable drive, plug-and-play backup.',
        'price': 320000,
        'compare_at_price': 380000,
        'sku': 'CA-SEA-1TB',
        'stock_quantity': 18,
        'is_active': True,
        'category_slug': 'computer-accessories',
        'images': [{'url': '/products/seagate-1tb-portable-external-hdd.jpg', 'alt_text': 'Seagate 1TB Portable External HDD', 'position': 0}],
    },
    {
        'name': 'Logitech MK270 Wireless Keyboard & Mouse',
        'slug': 'logitech-mk270-wireless-keyboard-mouse',
        'description': 'Full-size wireless combo with 24-month keyboard battery life.',
        'price': 165000,
        'compare_at_price': None,
        'sku': 'CA-LOG-MK270',
        'stock_quantity': 20,
        'is_active': True,
        'category_slug': 'computer-accessories',
        'images': [{'url': 'https://placehold.co/800x800/0f766e/ffffff.png?text=Logitech+MK270+Wireless+Keyboard+%26+Mouse&font=roboto', 'alt_text': 'Logitech MK270 Wireless Keyboard & Mouse', 'position': 0}],
    },
    {
        'name': 'Laptop Cooling Pad with 5 Fans',
        'slug': 'laptop-cooling-pad-with-5-fans',
        'description': 'Adjustable-height cooling stand with five quiet fans.',
        'price': 95000,
        'compare_at_price': 120000,
        'sku': 'CA-COOL-5F',
        'stock_quantity': 22,
        'is_active': True,
        'category_slug': 'computer-accessories',
        'images': [{'url': 'https://placehold.co/800x800/0f766e/ffffff.png?text=Laptop+Cooling+Pad+with+5+Fans&font=roboto', 'alt_text': 'Laptop Cooling Pad with 5 Fans', 'position': 0}],
    },
    {
        'name': 'HP Wired Optical Mouse USB',
        'slug': 'hp-wired-optical-mouse-usb',
        'description': '1000dpi ambidextrous wired mouse.',
        'price': 28000,
        'compare_at_price': None,
        'sku': 'CA-HP-MOUSE',
        'stock_quantity': 60,
        'is_active': True,
        'category_slug': 'computer-accessories',
        'images': [{'url': '/products/hp-wired-optical-mouse-usb.jpg', 'alt_text': 'HP Wired Optical Mouse USB', 'position': 0}],
    },
    {
        'name': 'Samsung Galaxy Tab A9+ 11" 64GB',
        'slug': 'samsung-galaxy-tab-a9-11-64gb',
        'description': '11-inch 90Hz display, 64GB storage, quad speakers.',
        'price': 1180000,
        'compare_at_price': 1350000,
        'sku': 'TAB-SAM-A9P',
        'stock_quantity': 10,
        'is_active': True,
        'category_slug': 'tablets',
        'images': [{'url': '/products/samsung-galaxy-tab-a9-11-64gb.png', 'alt_text': 'Samsung Galaxy Tab A9+ 11" 64GB', 'position': 0}],
    },
    {
        'name': 'Lenovo Tab M10 HD 4GB/64GB',
        'slug': 'lenovo-tab-m10-hd-4gb-64gb',
        'description': '10.1-inch HD tablet with Dolby Atmos and long battery life.',
        'price': 780000,
        'compare_at_price': None,
        'sku': 'TAB-LEN-M10',
        'stock_quantity': 12,
        'is_active': True,
        'category_slug': 'tablets',
        'images': [{'url': '/products/lenovo-tab-m10-hd-4gb-64gb.jpg', 'alt_text': 'Lenovo Tab M10 HD 4GB/64GB', 'position': 0}],
    },
    {
        'name': 'Amazon Fire HD 10 Tablet 32GB',
        'slug': 'amazon-fire-hd-10-tablet-32gb',
        'description': '10.1-inch Full HD tablet for reading and streaming.',
        'price': 620000,
        'compare_at_price': 720000,
        'sku': 'TAB-AMZ-HD10',
        'stock_quantity': 8,
        'is_active': True,
        'category_slug': 'tablets',
        'images': [{'url': '/products/amazon-fire-hd-10-tablet-32gb.jpg', 'alt_text': 'Amazon Fire HD 10 Tablet 32GB', 'position': 0}],
    },
    {
        'name': 'Hikvision 4MP ColorVu Dome Camera',
        'slug': 'hikvision-4mp-colorvu-dome-camera',
        'description': 'Full-colour night imaging, built-in mic, IP67 weatherproof.',
        'price': 320000,
        'compare_at_price': 380000,
        'sku': 'CC-HIK-4MPDOME',
        'stock_quantity': 20,
        'is_active': True,
        'category_slug': 'cctv-security-cameras',
        'images': [{'url': '/products/hikvision-4mp-colorvu-dome-camera.jpg', 'alt_text': 'Hikvision 4MP ColorVu Dome Camera', 'position': 0}],
    },
    {
        'name': 'Dahua 2MP HDCVI Bullet Camera',
        'slug': 'dahua-2mp-hdcvi-bullet-camera',
        'description': '1080p bullet camera with 30m infrared night range.',
        'price': 185000,
        'compare_at_price': None,
        'sku': 'CC-DAH-2MPBUL',
        'stock_quantity': 25,
        'is_active': True,
        'category_slug': 'cctv-security-cameras',
        'images': [{'url': '/products/dahua-2mp-hdcvi-bullet-camera.jpg', 'alt_text': 'Dahua 2MP HDCVI Bullet Camera', 'position': 0}],
    },
    {
        'name': 'Hikvision 8-Channel DVR with 1TB HDD',
        'slug': 'hikvision-8-channel-dvr-with-1tb-hdd',
        'description': '8-channel DVR pre-fitted with a 1TB surveillance drive.',
        'price': 890000,
        'compare_at_price': 990000,
        'sku': 'CC-HIK-DVR8',
        'stock_quantity': 9,
        'is_active': True,
        'category_slug': 'cctv-security-cameras',
        'images': [{'url': 'https://placehold.co/800x800/0f766e/ffffff.png?text=Hikvision+8-Channel+DVR+with+1TB+HDD&font=roboto', 'alt_text': 'Hikvision 8-Channel DVR with 1TB HDD', 'position': 0}],
    },
    {
        'name': 'Wireless Indoor PTZ Camera 3MP',
        'slug': 'wireless-indoor-ptz-camera-3mp',
        'description': 'Pan-tilt Wi-Fi camera with two-way audio and motion tracking.',
        'price': 195000,
        'compare_at_price': None,
        'sku': 'CC-PTZ-3MP',
        'stock_quantity': 22,
        'is_active': True,
        'category_slug': 'cctv-security-cameras',
        'images': [{'url': '/products/wireless-indoor-ptz-camera-3mp.jpg', 'alt_text': 'Wireless Indoor PTZ Camera 3MP', 'position': 0}],
    },
    {
        'name': 'CCTV Site Survey & Quotation',
        'slug': 'cctv-site-survey-quotation',
        'description': 'A technician visits, assesses coverage and gives a written quote.',
        'price': 50000,
        'compare_at_price': None,
        'sku': 'SVC-SURVEY',
        'stock_quantity': 100,
        'is_active': True,
        'category_slug': 'installation-services',
        'images': [{'url': '/products/cctv-site-survey-quotation.jpg', 'alt_text': 'CCTV Site Survey & Quotation', 'position': 0}],
    },
    {
        'name': 'Structured Network Cabling (per point)',
        'slug': 'structured-network-cabling-per-point',
        'description': 'Cat6 data point run, terminated and tested. Price per point.',
        'price': 85000,
        'compare_at_price': None,
        'sku': 'SVC-CABLE-PT',
        'stock_quantity': 100,
        'is_active': True,
        'category_slug': 'installation-services',
        'images': [{'url': '/products/structured-network-cabling-per-point.jpg', 'alt_text': 'Structured Network Cabling (per point)', 'position': 0}],
    },
    {
        'name': 'Annual CCTV Maintenance Contract',
        'slug': 'annual-cctv-maintenance-contract',
        'description': 'Two scheduled service visits a year plus priority callouts.',
        'price': 450000,
        'compare_at_price': 520000,
        'sku': 'SVC-CCTV-AMC',
        'stock_quantity': 50,
        'is_active': True,
        'category_slug': 'installation-services',
        'images': [{'url': '/products/annual-cctv-maintenance-contract.jpg', 'alt_text': 'Annual CCTV Maintenance Contract', 'position': 0}],
    },
]

ADS = [
    {'advertiser_name': 'Hikvision ColorVu', 'media_url': '/banners/Hikvision-ultra-series-PTZ-pc.jpg', 'media_type': 'IMAGE', 'link_url': '/products?category=cctv-security-cameras',
     'placement': 'SIDEBAR', 'starts_at': '2026-08-27 15:05:32.047417', 'ends_at': '2027-08-28 15:05:32.047417', 'is_active': True},
    {'advertiser_name': 'AOV SolarVu', 'media_url': '/banners/AOV-SolarVu-Cameras_homepage-banner.jpg', 'media_type': 'IMAGE', 'link_url': '/products?category=cctv-security-cameras',
     'placement': 'SIDEBAR', 'starts_at': '2026-08-27 15:05:32.047417', 'ends_at': '2027-08-28 15:05:32.047417', 'is_active': True},
    {'advertiser_name': 'Hikvision DeepinView', 'media_url': '/banners/deepinviewx-top-pc-banner.jpg', 'media_type': 'IMAGE', 'link_url': '/products?category=cctv-security-cameras',
     'placement': 'SIDEBAR', 'starts_at': '2026-08-27 15:05:32.047417', 'ends_at': '2027-08-28 15:05:32.047417', 'is_active': True},
    {'advertiser_name': 'Hikvision TandemVu', 'media_url': '/banners/TandemVu-PTZ-pc.jpg', 'media_type': 'IMAGE', 'link_url': '/products?category=cctv-security-cameras',
     'placement': 'HOMEPAGE_MID', 'starts_at': '2026-08-27 15:05:32.047417', 'ends_at': '2027-08-28 15:05:32.047417', 'is_active': True},
    {'advertiser_name': 'Hikvision Anti-Corrosion', 'media_url': '/banners/Hikvision-Anti-corrosion-series-camera-pc-banner.jpg', 'media_type': 'IMAGE', 'link_url': '/products?category=cctv-security-cameras',
     'placement': 'HOMEPAGE_MID', 'starts_at': '2026-08-27 15:05:32.047417', 'ends_at': '2027-08-28 15:05:32.047417', 'is_active': True},
    {'advertiser_name': 'Hikvision DeepinView', 'media_url': '/banners/Deepinview-banner.png', 'media_type': 'IMAGE', 'link_url': '/products?category=cctv-security-cameras',
     'placement': 'PRODUCT_LIST', 'starts_at': '2026-08-27 15:05:32.047417', 'ends_at': '2027-08-28 15:05:32.047417', 'is_active': True},
]
